#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Algorithm-Merge
Version  : 0.08
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/J/JS/JSMITH/Algorithm-Merge-0.08.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/J/JS/JSMITH/Algorithm-Merge-0.08.tar.gz
Source1  : http://http.debian.net/debian/pool/main/liba/libalgorithm-merge-perl/libalgorithm-merge-perl_0.08-3.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Artistic-1.0 GPL-1.0
Requires: perl-Algorithm-Merge-license
Requires: perl-Algorithm-Merge-man
BuildRequires : perl(Algorithm::Diff)

%description
NAME
Algorithm::Merge - Three-way merge and diff
SYNOPSIS
use Algorithm::Merge qw(merge diff3 traverse_sequences3);

%package license
Summary: license components for the perl-Algorithm-Merge package.
Group: Default

%description license
license components for the perl-Algorithm-Merge package.


%package man
Summary: man components for the perl-Algorithm-Merge package.
Group: Default

%description man
man components for the perl-Algorithm-Merge package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Algorithm-Merge-0.08
mkdir -p %{_topdir}/BUILD/Algorithm-Merge-0.08/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Algorithm-Merge-0.08/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Algorithm-Merge
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Algorithm-Merge/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Algorithm/Merge.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Algorithm-Merge/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Algorithm::Merge.3
